# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2022-10-03 15:26
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='PresenceOfTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Project title')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Project start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Project end date')),
                ('estimated_design', models.PositiveSmallIntegerField(verbose_name='Estimated design hours')),
                ('actual_design', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Actual design hours')),
                ('estimated_development', models.PositiveSmallIntegerField(verbose_name='Estimated development hours')),
                ('actual_development', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Actual development hours')),
                ('estimated_testing', models.PositiveSmallIntegerField(verbose_name='Estimated testing hours')),
                ('actual_testing', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Actual testing hours')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Project modification date')),
                ('info', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='projects.Project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'change',
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(through='projects.PresenceOfTags', to='projects.ProjectTag'),
        ),
        migrations.AddField(
            model_name='presenceoftags',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='presenceoftags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectTag'),
        ),
    ]
