# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2022-10-03 10:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_design',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Actual design hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_development',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Actual development hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_testing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Actual testing hours'),
        ),
    ]
